pipeline {
    agent any
    environment {
        DOCKER_IMAGE = 'deveshrathore13/dynamic:latest' // Replace with your Docker image name
    }
    stages {
        stage('Build') {
            steps {
                script {
                    // Build Docker image
                    dockerImage = docker.build(DOCKER_IMAGE)
                }
            }
        }
        stage('Push') {
            steps {
                script {
                    // Push Docker image to Docker Hub or your registry
                    docker.withRegistry('https://index.docker.io/v1/', 'docker-credentials') {
                        dockerImage.push()
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    // Deploy to Kubernetes using kubectl or Kubernetes plugin
                    kubernetesDeploy(configs: 'path/to/kubernetes/configs/*.yaml', kubeconfigId: 'kubeconfig')
                }
            }
        }
    }
}

